// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9iwqV0pUYPoGtjspkefMFBG0zdpnkKZw',
    appId: '1:312829297511:web:800cd658fb97a8b8c2a5c2',
    messagingSenderId: '312829297511',
    projectId: 'blood-donation-68ad6',
    authDomain: 'blood-donation-68ad6.firebaseapp.com',
    storageBucket: 'blood-donation-68ad6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5wqgsvsEygb7dbbtLoQzqlFztTW5h0Xk',
    appId: '1:312829297511:android:5818076a9631633ac2a5c2',
    messagingSenderId: '312829297511',
    projectId: 'blood-donation-68ad6',
    storageBucket: 'blood-donation-68ad6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn4QWV3HqbOpd5VtaMW05krqDNWutNfPM',
    appId: '1:312829297511:ios:7f54eb5ded055429c2a5c2',
    messagingSenderId: '312829297511',
    projectId: 'blood-donation-68ad6',
    storageBucket: 'blood-donation-68ad6.appspot.com',
    iosBundleId: 'com.example.bloodDonationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn4QWV3HqbOpd5VtaMW05krqDNWutNfPM',
    appId: '1:312829297511:ios:cb0a8ce1a1bd125fc2a5c2',
    messagingSenderId: '312829297511',
    projectId: 'blood-donation-68ad6',
    storageBucket: 'blood-donation-68ad6.appspot.com',
    iosBundleId: 'com.example.bloodDonationApp.RunnerTests',
  );
}
